// FastRPC IDL interface for GGML HTP

#ifndef HTP_IDL
#define HTP_IDL

#include "AEEStdDef.idl"
#include "remote.idl"

interface htp_iface : remote_handle64 {
    AEEResult start(in uint32 sess_id, in uint64 dsp_queue_id, in uint32 n_hvx, in uint32 use_hmx);
    AEEResult stop();
    AEEResult mmap(in uint32 fd, in uint32 size, in uint32 pinned);
    AEEResult munmap(in uint32 fd);
    AEEResult enable_etm();
    AEEResult disable_etm();
};

#endif /* HTP_IDL */
