export const MODELS = {
  SMOL_LM_3: {
    name: 'SmolLM3 3B (Q4_K_M)',
    repo: 'ggml-org/SmolLM3-3B-GGUF',
    filename: 'SmolLM3-Q4_K_M.gguf',
    mmproj: undefined,
    size: '1.78GB',
  },
  GEMMA_3N_E2B: {
    name: 'Gemma 3N E2B IT (Q3_K_M)',
    repo: 'unsloth/gemma-3n-E2B-it-GGUF',
    filename: 'gemma-3n-E2B-it-Q3_K_M.gguf',
    mmproj: undefined,
    size: '2.31GB',
  },
  GEMMA_3N_E4B: {
    name: 'Gemma 3N E4B IT (Q3_K_M)',
    repo: 'unsloth/gemma-3n-E4B-it-GGUF',
    filename: 'gemma-3n-E4B-it-Q3_K_M.gguf',
    mmproj: undefined,
    size: '3.44GB',
  },
  QWEN_3_4B: {
    name: 'Qwen 3 4B (Q3_K_M)',
    repo: 'unsloth/Qwen3-4B-GGUF',
    filename: 'Qwen3-4B-Q3_K_M.gguf',
    mmproj: undefined,
    size: '1.93GB',
  },
  QWEN_3_5_4B_MTP: {
    name: 'Qwen3.5 4B MTP (Q8_0)',
    repo: 'unsloth/Qwen3.5-4B-MTP-GGUF',
    filename: 'Qwen3.5-4B-Q8_0.gguf',
    mmproj: undefined,
    size: '4.3GB',
  },
  QWEN_3_6_35B_A3B_MTP: {
    name: 'Qwen3.6 35B A3B MTP (Q8_0)',
    repo: 'unsloth/Qwen3.6-35B-A3B-MTP-GGUF',
    filename: 'Qwen3.6-35B-A3B-Q8_0.gguf',
    mmproj: undefined,
    size: '37.8GB',
  },
  SMOL_VLM_500M: {
    name: 'SmolVLM 500M Instruct (Q8_0)',
    repo: 'ggml-org/SmolVLM-500M-Instruct-GGUF',
    filename: 'SmolVLM-500M-Instruct-Q8_0.gguf',
    mmproj: 'mmproj-SmolVLM-500M-Instruct-Q8_0.gguf',
    size: '416MB',
  },
  SMOL_VLM_2_2B: {
    name: 'SmolVLM2 2.2B Instruct (Q4_K_M)',
    repo: 'ggml-org/SmolVLM2-2.2B-Instruct-GGUF',
    filename: 'SmolVLM2-2.2B-Instruct-Q4_K_M.gguf',
    mmproj: 'mmproj-SmolVLM2-2.2B-Instruct-Q8_0.gguf',
    size: '1.8GB (model) + 565MB (mmproj)',
  },
  INTERNVL3_2B: {
    name: 'InternVL3 2B (Q8_0)',
    repo: 'ggml-org/InternVL3-2B-Instruct-GGUF',
    filename: 'InternVL3-2B-Instruct-Q8_0.gguf',
    mmproj: 'mmproj-InternVL3-2B-Instruct-Q8_0.gguf',
    size: '1.89GB (model) + 337MB (mmproj)',
  },
  QWEN2_5_VL_3B: {
    name: 'Qwen2.5 VL 3B (Q4_K_M)',
    repo: 'ggml-org/Qwen2.5-VL-3B-Instruct-GGUF',
    filename: 'Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf',
    mmproj: 'mmproj-Qwen2.5-VL-3B-Instruct-Q8_0.gguf',
    size: '1.93GB (model) + 845MB (mmproj)',
  },
  QWEN2_5_OMNI_3B: {
    name: 'Qwen2.5 Omni 3B (Q4_K_M)',
    repo: 'ggml-org/Qwen2.5-Omni-3B-GGUF',
    filename: 'Qwen2.5-Omni-3B-Q4_K_M.gguf',
    mmproj: 'mmproj-Qwen2.5-Omni-3B-Q8_0.gguf',
    size: '2.1GB (model) + 1.54GB (mmproj)',
  },
  GEMMA_3_4B_QAT: {
    name: 'Gemma 3 4B IT QAT (Q3_K_M)',
    repo: 'unsloth/gemma-3-4b-it-qat-GGUF',
    filename: 'gemma-3-4b-it-qat-Q3_K_M.gguf',
    mmproj: 'mmproj-BF16.gguf',
    size: '1.95GB (model) + 881MB (mmproj)',
  },
  ULTRAVOX_V0_5_LLAMA_3_2_1B: {
    name: 'Ultravox V0.5 Llama 3.2 1B (Q4_K_M)',
    repo: 'ggml-org/ultravox-v0_5-llama-3_2-1b-GGUF',
    filename: 'Llama-3.2-1B-Instruct-Q4_K_M.gguf',
    mmproj: 'mmproj-ultravox-v0_5-llama-3_2-1b-f16.gguf',
    size: '808MB (model) + 1.37GB (mmproj)',
  },
  OUTE_TTS_0_3: {
    name: 'OuteTTS 0.3 500M (Q4_K_M) + WavTokenizer (FP16)',
    repo: 'OuteAI/OuteTTS-0.3-500M-GGUF',
    filename: 'OuteTTS-0.3-500M-Q4_K_M.gguf',
    mmproj: undefined,
    size: '454MB (model) + 170MB (vocoder)',
    vocoder: {
      repo: 'hans00/codec.cpp-gguf',
      filename: 'wavtokenizer-large-speech-75tokens.gguf',
      size: '170MB',
    },
  },
  OUTE_TTS_1_0: {
    name: 'OuteTTS 1.0 0.6B (Q4_K_M) + DAC (FP16)',
    repo: 'OuteAI/OuteTTS-1.0-0.6B-GGUF',
    filename: 'OuteTTS-1.0-0.6B-Q4_K_M.gguf',
    mmproj: undefined,
    size: '454MB (model) + 296MB (vocoder)',
    vocoder: {
      repo: 'hans00/codec.cpp-gguf',
      filename: 'ibm-research--DAC.speech.gguf',
      size: '296MB',
    },
  },
  SOPRANO_1_1: {
    name: 'Soprano-1.1 80M (F16) + codec (FP32)',
    repo: 'hans00/Soprano-1.1-80M-GGUF',
    filename: 'Soprano-1.1-80M.F16.gguf',
    mmproj: undefined,
    size: '160MB (model) + 121MB (vocoder)',
    vocoder: {
      repo: 'hans00/Soprano-1.1-80M-GGUF',
      filename: 'codec-F32.gguf',
      size: '121MB',
    },
  },
  NEUTTS_NANO: {
    name: 'NeuTTS Nano (Q4_K_M) + NeuCodec (Q8_0)',
    repo: 'hans00/NeuTTS-Nano-GGUF',
    filename: 'neutts-nano-q4_k_m.gguf',
    mmproj: undefined,
    size: '210MB (model) + 342MB (codec)',
    vocoder: {
      repo: 'hans00/NeuTTS-Nano-GGUF',
      filename: 'codec-q8_0.gguf',
      size: '342MB',
    },
  },
  NEUTTS_AIR: {
    name: 'NeuTTS Air (Q4_K_M) + NeuCodec (Q8_0)',
    repo: 'hans00/NeuTTS-Air-GGUF',
    filename: 'neutts-air-q4_k_m.gguf',
    mmproj: undefined,
    size: '596MB (model) + 342MB (codec)',
    vocoder: {
      repo: 'hans00/NeuTTS-Air-GGUF',
      filename: 'codec-q8_0.gguf',
      size: '342MB',
    },
  },
  CSM_1B: {
    name: 'CSM-1B Sesame (Q4_K_M) + Mimi + codec_lm (Q8_0)',
    repo: 'hans00/CSM-1B-GGUF',
    filename: 'csm-1b-q4_k_m.gguf',
    mmproj: undefined,
    size: '770MB (model) + 803MB (codec+codec_lm)',
    vocoder: {
      repo: 'hans00/CSM-1B-GGUF',
      filename: 'codec-q8_0.gguf',
      size: '803MB',
    },
  },
  QWEN3_TTS_0_6B: {
    name: 'Qwen3-TTS 0.6B (Q4_K_M) + 12Hz codec + codec_lm (Q8_0)',
    repo: 'hans00/Qwen3-TTS-12Hz-0.6B-GGUF',
    filename: 'qwen3-tts-0.6b-q4_k_m.gguf',
    mmproj: undefined,
    size: '257MB (model) + 565MB (codec+codec_lm)',
    vocoder: {
      repo: 'hans00/Qwen3-TTS-12Hz-0.6B-GGUF',
      filename: 'codec-q8_0.gguf',
      size: '565MB',
    },
  },
  MOSS_TTS_REALTIME: {
    // Backbone converted with codec.cpp's bundled llama.cpp (Q8_0 — the
    // Q4_K_M backbone drifts).  Streaming text↔audio interleave with a
    // per-codebook repetition penalty; stops on eos_code_c0.
    name: 'MOSS-TTS-Realtime (Q8_0) + MOSS-Audio + codec_lm (Q5_K_M)',
    repo: 'hans00/MOSS-TTS-Realtime-GGUF',
    filename: 'moss-tts-realtime-q8_0.gguf',
    mmproj: undefined,
    size: '1.8GB (model) + 1.8GB (codec+codec_lm)',
    vocoder: {
      repo: 'hans00/MOSS-TTS-Realtime-GGUF',
      filename: 'codec-q5_k_m.gguf',
      size: '1.8GB',
    },
  },
  MOSS_TTSD_V05: {
    // v0.5 is codec.cpp's validated reference; the backbone MUST be converted
    // with codec.cpp's bundled llama.cpp (not a standalone checkout) or the
    // Qwen3 numerics drift into babble.  Q8_0 backbone reproduces the input
    // and stops on eos_code_c0.  Prompt uses the [S1] dialogue format.
    name: 'MOSS-TTSD v0.5 (Q8_0) + XY-Tokenizer + codec_lm (Q5_K_M)',
    repo: 'hans00/MOSS-TTSD-v0.5-GGUF',
    filename: 'moss-ttsd-v0.5-q8_0.gguf',
    mmproj: undefined,
    size: '1.8GB (model) + 1.1GB (codec+codec_lm)',
    vocoder: {
      repo: 'hans00/MOSS-TTSD-v0.5-GGUF',
      filename: 'codec-q5_k_m.gguf',
      size: '1.1GB',
    },
  },
  CHATTERBOX_MULTILINGUAL: {
    name: 'Chatterbox Multilingual T3 (Q4_K_M) + S3G + codec_lm (Q4_K_M)',
    repo: 'hans00/Chatterbox-Multilingual-TTS-GGUF',
    filename: 'chatterbox-mtl-t3-q4_k_m.gguf',
    mmproj: undefined,
    size: '289MB (T3) + 178MB (codec+codec_lm)',
    vocoder: {
      repo: 'hans00/Chatterbox-Multilingual-TTS-GGUF',
      filename: 'chatterbox-mtl-codec-q4_k_m.gguf',
      size: '178MB',
    },
  },
  BLUEMAGPIE_TTS: {
    name: 'BlueMagpie-TTS Barbet-1B (Q4_K_M) + AudioVAE (Q8_0) + codec_lm',
    repo: 'hans00/BlueMagpie-TTS-GGUF',
    filename: 'BlueMagpie-Barbet-1B-q4_k_m.gguf',
    mmproj: undefined,
    size: '661MB (backbone) + 1.04GB (codec+codec_lm)',
    vocoder: {
      repo: 'hans00/BlueMagpie-TTS-GGUF',
      filename: 'BlueMagpie-AudioVAE-q8_0.gguf',
      size: '1.04GB',
    },
  },
  EMBEDDINGGEMMA_300M: {
    name: 'EmbeddingGemma 300M (Q8_0)',
    repo: 'ggml-org/embeddinggemma-300M-GGUF',
    filename: 'embeddinggemma-300M-Q8_0.gguf',
    mmproj: undefined,
    size: '329MB',
    embedding: true,
  },
  NOMIC_EMBED_TEXT_V1_5: {
    name: 'Nomic Embed Text v1.5 (Q8_0)',
    repo: 'nomic-ai/nomic-embed-text-v1.5-GGUF',
    filename: 'nomic-embed-text-v1.5.Q8_0.gguf',
    mmproj: undefined,
    embedding: true,
    size: '146MB',
  },
  SNOWFLAKE_ARCTIC_EMBED_M_V1_5: {
    name: 'Snowflake Arctic Embed M v1.5 (Q8_0)',
    repo: 'Snowflake/snowflake-arctic-embed-m-v1.5',
    filename: 'gguf/snowflake-arctic-embed-m-v1.5-q8_0.gguf',
    mmproj: undefined,
    embedding: true,
    size: '118MB',
  },
  MIXEDBREAD_AI_EMBED_LARGE_V1: {
    name: 'MixedBread AI Embed Large v1 (F16)',
    repo: 'mixedbread-ai/mxbai-embed-large-v1',
    filename: 'gguf/mxbai-embed-large-v1-f16.gguf',
    mmproj: undefined,
    embedding: true,
    size: '670MB',
  },
  BGE_RERANKER_V2_M3: {
    name: 'BGE Reranker v2 M3 (Q8_0)',
    repo: 'gpustack/bge-reranker-v2-m3-GGUF',
    filename: 'bge-reranker-v2-m3-Q8_0.gguf',
    mmproj: undefined,
    ranking: true,
    size: '636MB',
  },
}

export const HUGGINGFACE_BASE_URL = 'https://huggingface.co'

export const getModelDownloadUrl = (repo: string, filename: string) =>
  `${HUGGINGFACE_BASE_URL}/${repo}/resolve/main/${filename}?download=true`
